
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Feb 23 2025 16:23:17 PST (Feb 24 2025 00:23:17 UTC)

// Verification Directory fv/counter_8_bit 

module counter_8_bit(clk, rstn, count);
  input clk, rstn;
  output [7:0] count;
  wire clk, rstn;
  wire [7:0] count;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, \count[0]_45 , n_0, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_14, n_15, n_16, n_17, n_20, n_24, n_25;
  SDFFR_X2 \count_reg[7] (.RN (rstn), .CK (clk), .D (n_0), .SE (n_20),
       .SI (count[7]), .Q (count[7]), .QN (n_0));
  DFFR_X2 \count_reg[6] (.RN (rstn), .CK (clk), .D (n_24), .Q
       (count[6]), .QN (UNCONNECTED));
  NAND2_X1 g187__5107(.A1 (n_16), .A2 (count[6]), .ZN (n_20));
  DFFR_X2 \count_reg[5] (.RN (rstn), .CK (clk), .D (n_17), .Q
       (count[5]), .QN (n_14));
  AOI21_X1 g189__6260(.A (n_16), .B1 (n_15), .B2 (n_14), .ZN (n_17));
  DFFR_X2 \count_reg[4] (.RN (rstn), .CK (clk), .D (n_25), .Q
       (count[4]), .QN (UNCONNECTED0));
  NOR2_X1 g192__4319(.A1 (n_15), .A2 (n_14), .ZN (n_16));
  NAND2_X1 g195__8428(.A1 (n_9), .A2 (count[4]), .ZN (n_15));
  DFFR_X2 \count_reg[3] (.RN (rstn), .CK (clk), .D (n_10), .Q
       (count[3]), .QN (n_7));
  AOI21_X1 g197__6783(.A (n_9), .B1 (n_8), .B2 (n_7), .ZN (n_10));
  NOR2_X1 g200__3680(.A1 (n_8), .A2 (n_7), .ZN (n_9));
  DFFR_X2 \count_reg[2] (.RN (rstn), .CK (clk), .D (n_6), .Q
       (count[2]), .QN (UNCONNECTED1));
  DFFR_X2 \count_reg[1] (.RN (rstn), .CK (clk), .D (n_5), .Q
       (count[1]), .QN (UNCONNECTED2));
  XNOR2_X1 g201__1617(.A (n_4), .B (count[2]), .ZN (n_6));
  NAND2_X1 g203__2802(.A1 (n_3), .A2 (count[2]), .ZN (n_8));
  AND2_X1 g205__1705(.A1 (n_4), .A2 (n_2), .ZN (n_5));
  INV_X1 g204(.A (n_4), .ZN (n_3));
  OR2_X1 g207__5122(.A1 (count[0]), .A2 (count[1]), .ZN (n_2));
  NAND2_X1 g208__8246(.A1 (count[1]), .A2 (count[0]), .ZN (n_4));
  DFFR_X1 \count_reg[0] (.RN (rstn), .CK (clk), .D (\count[0]_45 ), .Q
       (UNCONNECTED3), .QN (\count[0]_45 ));
  INV_X2 g211(.A (\count[0]_45 ), .ZN (count[0]));
  XOR2_X1 g2(.A (n_16), .B (count[6]), .Z (n_24));
  XOR2_X1 g221(.A (n_9), .B (count[4]), .Z (n_25));
endmodule

