
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Mar 27 2025 17:58:13 PDT (Mar 28 2025 00:58:13 UTC)

// Verification Directory fv/counter_8_bit 

module counter_8_bit(clk, rstn, count);
  input clk, rstn;
  output [7:0] count;
  wire clk, rstn;
  wire [7:0] count;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  DFFR_X1 count_reg_7(.RN (rstn), .CK (clk), .D (n_16), .Q (count[7]),
       .QN (UNCONNECTED));
  XNOR2_X1 g187__2398(.A (n_15), .B (count[7]), .ZN (n_16));
  DFFR_X1 count_reg_6(.RN (rstn), .CK (clk), .D (n_1), .Q (count[6]),
       .QN (UNCONNECTED0));
  DFFR_X1 count_reg_5(.RN (rstn), .CK (clk), .D (n_14), .Q (count[5]),
       .QN (n_2));
  NAND2_X1 g191__5107(.A1 (n_5), .A2 (count[6]), .ZN (n_15));
  AOI21_X1 g193__6260(.A (n_5), .B1 (n_13), .B2 (n_2), .ZN (n_14));
  DFFR_X1 count_reg_4(.RN (rstn), .CK (clk), .D (n_0), .Q (count[4]),
       .QN (UNCONNECTED1));
  NOR2_X1 g196__4319(.A1 (n_13), .A2 (n_2), .ZN (n_5));
  DFFR_X1 count_reg_3(.RN (rstn), .CK (clk), .D (n_12), .Q (count[3]),
       .QN (n_3));
  NAND2_X1 g199__8428(.A1 (n_4), .A2 (count[4]), .ZN (n_13));
  AOI21_X1 g201__5526(.A (n_4), .B1 (n_10), .B2 (n_3), .ZN (n_12));
  DFFR_X1 count_reg_2(.RN (rstn), .CK (clk), .D (n_11), .Q (count[2]),
       .QN (UNCONNECTED2));
  NOR2_X1 g204__6783(.A1 (n_10), .A2 (n_3), .ZN (n_4));
  XNOR2_X1 g205__3680(.A (n_7), .B (count[2]), .ZN (n_11));
  DFFR_X1 count_reg_1(.RN (rstn), .CK (clk), .D (n_8), .Q (count[1]),
       .QN (UNCONNECTED3));
  NAND2_X1 g207__1617(.A1 (n_9), .A2 (count[2]), .ZN (n_10));
  INV_X1 g208(.A (n_7), .ZN (n_9));
  AND2_X1 g209__2802(.A1 (n_7), .A2 (n_6), .ZN (n_8));
  DFFR_X1 count_reg_0(.RN (rstn), .CK (clk), .D (n_17), .Q (count[0]),
       .QN (n_17));
  OR2_X1 g211__1705(.A1 (count[1]), .A2 (count[0]), .ZN (n_6));
  NAND2_X1 g212__5122(.A1 (count[1]), .A2 (count[0]), .ZN (n_7));
  XOR2_X1 g2__8246(.A (n_5), .B (count[6]), .Z (n_1));
  XOR2_X1 g227__7098(.A (n_4), .B (count[4]), .Z (n_0));
endmodule

